spring:
  # Naver SMTP Server 사용
  mail:
    host: smtp.naver.com #smtp 서버 주소
    port: 465 # 메일 인증서버 포트
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            enable: true #반드시 필요 -> SSL 필요로 되어있으면