debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.gxdxx.programadmin: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: secret

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

---

spring:
  config.activate.on-profile: testdb
  datasource:
    url: jdbc:h2:mem:programadmin;mode=mysql
    driverClassName: org.h2.Driver
  sql.init.mode: always
  test.database.replace: none
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-templates-location: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

---

